# Step 1: Loading and Processing

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#Load Dataset
housing = fetch_california_housing()
housing_df = pd.DataFrame(housing.data, columns=housing.feature_names)
housing_df['MedhouseVal']=housing.target

In [ ]:
#DataCleaning Log & Flagging

#Checking for nulls and documenting the process
# Define the log entry
log_data = {
    "Issue": ["None (Missing Values Check)"],
    "Action": ["Verification Only"],
    "Business Impact": ["Data integrity confirmed; ensures model reliability for price prediction"]
}
#Create the dataframe
cleaning_log=pd.DataFrame(log_data)

In [ ]:
# Scaling: Essential for SVR and Linear Regression
scaler = StandardScaler()
x = housing_df.drop('MedhouseVal', axis=1)
y = housing_df['MedhouseVal']
x_scaled = scaler.fit_transform(X)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

In [ ]:
x_train

array([[-0.32165429,  0.34647803, -0.16625886, ...,  0.05980847,
        -1.36797628,  1.26764451],
       [-0.03061993,  1.61780729, -0.3861807 , ..., -0.12830597,
        -0.87169852,  0.7036268 ],
       [ 0.1503488 , -1.95780625,  0.08764093, ..., -0.03345346,
        -0.45501247, -0.45435647],
       ...,
       [-0.49283239,  0.58485227, -0.58294927, ...,  0.02517025,
        -0.74997001,  0.59381804],
       [ 0.97302487, -1.08376738,  0.39058403, ...,  0.01042151,
         0.91209231, -1.19306993],
       [-0.68174943,  1.85618152, -0.81905034, ..., -0.09262259,
         1.00104776, -1.42267006]])

In [ ]:
y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: MedhouseVal, Length: 4128, dtype: float64

In [ ]:
print("Data Cleaning log :")
print(cleaning_log)

Data Cleaning log :
                         Issue             Action  \
0  None (Missing Values Check)  Verification Only

                                     Business Impact
0  Data integrity confirmed; ensures model reliab...

**Linear Regression**

In [ ]:
#Implement the linear regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# 1. Initialize and Fit the Model
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

# 2. Make Predictions
lr_predictions = lr_model.predict(x_test)

# 3. Quick Check: Coefficients
# This shows how much each feature (like MedInc) affects the price
coeffs = pd.DataFrame(lr_model.coef_, x.columns, columns=['Coefficient'])
print("Feature Importance (Coefficients):")
print(coeffs.sort_values(by='Coefficient', ascending=False))

Feature Importance (Coefficients):
            Coefficient
MedInc         0.852382
AveBedrms      0.371132
HouseAge       0.122382
Population    -0.002298
AveOccup      -0.036624
AveRooms      -0.305116
Longitude     -0.868927
Latitude      -0.896635

In [ ]:
x_train

array([[-0.32165429,  0.34647803, -0.16625886, ...,  0.05980847,
        -1.36797628,  1.26764451],
       [-0.03061993,  1.61780729, -0.3861807 , ..., -0.12830597,
        -0.87169852,  0.7036268 ],
       [ 0.1503488 , -1.95780625,  0.08764093, ..., -0.03345346,
        -0.45501247, -0.45435647],
       ...,
       [-0.49283239,  0.58485227, -0.58294927, ...,  0.02517025,
        -0.74997001,  0.59381804],
       [ 0.97302487, -1.08376738,  0.39058403, ...,  0.01042151,
         0.91209231, -1.19306993],
       [-0.68174943,  1.85618152, -0.81905034, ..., -0.09262259,
         1.00104776, -1.42267006]])

In [ ]:
y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: MedhouseVal, Length: 4128, dtype: float64

In [ ]:
r2_score(y_test, lr_predictions)

0.5757877060324511

Linear Regression finds the "Line of Best Fit" by minimizing the Residual Sum of Squares (RSS). It calculates a weight (coefficient) for each input feature (e.g., Median Income, Average Rooms) to predict the target (House Value).

# Decision Tree Regressor  & Model Evaluation

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

# 1. Initialize and Fit the Model
# We set a max_depth to prevent the tree from growing infinitely (overfitting)
dt_model = DecisionTreeRegressor(max_depth=10, random_state=42)
dt_model.fit(X_train, y_train)

# 2. Make Predictions
dt_predictions = dt_model.predict(X_test)

# 3. Quick Performance Check
dt_mse = mean_squared_error(y_test, dt_predictions)
dt_r2 = r2_score(y_test, dt_predictions)

print(f"Decision Tree MSE: {dt_mse:.4f}")
print(f"Decision Tree R2 Score: {dt_r2:.4f}")

Decision Tree MSE: 0.4151
Decision Tree R2 Score: 0.6832

**Housing data often has "thresholds" (e.g., houses in a specific Latitude/Longitude range or with more than 3 bedrooms might jump in price). Decision Trees are excellent at capturing these non-linear relationships and interactions between features without needing complex transformations.**

# Random Forest Regressor &

# Gradient Boosting Regressor & Model Evaluation

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# 1. Initialize and Fit the Model

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)

# 2. Make Predictions
rf_predictions = rf_model.predict(x_test)

# 3. Calculate Metrics
rf_mse = mean_squared_error(y_test, rf_predictions)
rf_r2 = r2_score(y_test, rf_predictions)

print(f"Random Forest MSE: {rf_mse:.4f}")
print(f"Random Forest R2 Score: {rf_r2:.4f}")

Random Forest MSE: 0.2555
Random Forest R2 Score: 0.8050

**It is excellent for the California Housing dataset because it prevents overfitting, which is a common problem with single Decision Trees. By averaging the results of 100 trees, it handles the noise in housing prices**

# Gradient Boosting Regressor & Model Evaluation

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score

# 1. Initialize and Fit the Model
# learning_rate scales the contribution of each tree
gb_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gb_model.fit(X_train, y_train)

# 2. Make Predictions
gb_predictions = gb_model.predict(X_test)

# 3. Calculate Metrics
gb_mse = mean_squared_error(y_test, gb_predictions)
gb_r2 = r2_score(y_test, gb_predictions)

print(f"Gradient Boosting MSE: {gb_mse:.4f}")
print(f"Gradient Boosting R2 Score: {gb_r2:.4f}")

Gradient Boosting MSE: 0.2940
Gradient Boosting R2 Score: 0.7756

**It is highly flexible and usually provides the highest accuracy for regression tasks.**

# Support Vector Regressor

In [ ]:
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score

# 1. Initialize and Fit the Model
# 'C' controls the penalty for points outside the tube; 'epsilon' is the tube width
svr_model = SVR(kernel='rbf', C=1.0, epsilon=0.1)
svr_model.fit(X_train, y_train)

# 2. Make Predictions
svr_predictions = svr_model.predict(X_test)

# 3. Calculate Metrics
svr_mse = mean_squared_error(y_test, svr_predictions)
svr_r2 = r2_score(y_test, svr_predictions)

print(f"SVR MSE: {svr_mse:.4f}")
print(f"SVR R2 Score: {svr_r2:.4f}")

SVR MSE: 0.3552
SVR R2 Score: 0.7289

Support Vector Regression (SVR) works on the principle of finding a hyperplane that best fits the data while staying within a specific threshold ($\epsilon$). It uses the Kernel Trick to transform the data into a higher-dimensional space, making it possible to find a linear fit for non-linear data.